config/routes.rb
Cryptos::Application.routes.draw do
  resources :fiveminute_timed_assets

  resources :timed_assets

  resources :user_infos

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'NUKE', to: 'user_infos#NUKE'
  post 'start_log', to: 'staticpages#start_log'
  post 'do_old_assets_averaging', to: 'staticpages#do_old_assets_averaging'
  post 'NUKE_Averages', to: 'staticpages#NUKE_Averages'
  post 'Setup', to: 'staticpages#Setup'

  get "/homepage", to: 'staticpages#homepage'
  get "/about", to: 'staticpages#about'
  get "/database", to: 'staticpages#database'
  get "/worker_messages.html", to: 'staticpages#worker_messages'
  root 'staticpages#homepage'

  

end

app/models/fiveminute_timed_asset.rb
class FiveminuteTimedAsset < ActiveRecord::Base
end

app/controllers/fiveminute_timed_assets_controller.rb
class FiveminuteTimedAssetsController < ApplicationController
  before_action :set_fiveminute_timed_asset, only: [:show, :edit, :update, :destroy]

  # GET /fiveminute_timed_assets
  # GET /fiveminute_timed_assets.json
  def index
    @fiveminute_timed_assets = FiveminuteTimedAsset.last(900)
  end

  # GET /fiveminute_timed_assets/1
  # GET /fiveminute_timed_assets/1.json
  def show
  end

  # GET /fiveminute_timed_assets/new
  def new
    @fiveminute_timed_asset = FiveminuteTimedAsset.new
  end

  # GET /fiveminute_timed_assets/1/edit
  def edit
  end

  # POST /fiveminute_timed_assets
  # POST /fiveminute_timed_assets.json
  def create
    @fiveminute_timed_asset = FiveminuteTimedAsset.new(fiveminute_timed_asset_params)

    respond_to do |format|
      if @fiveminute_timed_asset.save
        format.html { redirect_to @fiveminute_timed_asset, notice: 'Fiveminute timed asset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fiveminute_timed_asset }
      else
        format.html { render action: 'new' }
        format.json { render json: @fiveminute_timed_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fiveminute_timed_assets/1
  # PATCH/PUT /fiveminute_timed_assets/1.json
  def update
    respond_to do |format|
      if @fiveminute_timed_asset.update(fiveminute_timed_asset_params)
        format.html { redirect_to @fiveminute_timed_asset, notice: 'Fiveminute timed asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fiveminute_timed_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fiveminute_timed_assets/1
  # DELETE /fiveminute_timed_assets/1.json
  def destroy
    @fiveminute_timed_asset.destroy
    respond_to do |format|
      format.html { redirect_to fiveminute_timed_assets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fiveminute_timed_asset
      @fiveminute_timed_asset = FiveminuteTimedAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fiveminute_timed_asset_params
      params.require(:fiveminute_timed_asset).permit(:BTC, :LTC, :PPC, :NMC, :XPM, :AsicMiner, :AsicMiner_small, :Advanced_Mining_Corp, :misc1, :misc2, :misc3, :comment, :time_changed)
    end
end

app/helpers/fiveminute_timed_assets_helper.rb
module FiveminuteTimedAssetsHelper
end

app/views/fiveminute_timed_assets/_form.html.erb
<%= form_for(@fiveminute_timed_asset) do |f| %>
  <% if @fiveminute_timed_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiveminute_timed_asset.errors.count, "error") %> prohibited this fiveminute_timed_asset from being saved:</h2>

      <ul>
      <% @fiveminute_timed_asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :BTC %><br>
    <%= f.text_field :BTC %>
  </div>
  <div class="field">
    <%= f.label :LTC %><br>
    <%= f.text_field :LTC %>
  </div>
  <div class="field">
    <%= f.label :PPC %><br>
    <%= f.text_field :PPC %>
  </div>
  <div class="field">
    <%= f.label :NMC %><br>
    <%= f.text_field :NMC %>
  </div>
  <div class="field">
    <%= f.label :XPM %><br>
    <%= f.text_field :XPM %>
  </div>
  <div class="field">
    <%= f.label :AsicMiner %><br>
    <%= f.text_field :AsicMiner %>
  </div>
  <div class="field">
    <%= f.label :AsicMiner_small %><br>
    <%= f.text_field :AsicMiner_small %>
  </div>
  <div class="field">
    <%= f.label :Advanced_Mining_Corp %><br>
    <%= f.text_field :Advanced_Mining_Corp %>
  </div>
  <div class="field">
    <%= f.label :misc1 %><br>
    <%= f.text_field :misc1 %>
  </div>
  <div class="field">
    <%= f.label :misc2 %><br>
    <%= f.text_field :misc2 %>
  </div>
  <div class="field">
    <%= f.label :misc3 %><br>
    <%= f.text_field :misc3 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :time_changed %><br>
    <%= f.datetime_select :time_changed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiveminute_timed_assets/edit.html.erb
<h1>Editing fiveminute_timed_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @fiveminute_timed_asset %> |
<%= link_to 'Back', fiveminute_timed_assets_path %>

app/views/fiveminute_timed_assets/index.html.erb
<h1>Listing fiveminute_timed_assets</h1>

<table>
  <thead>
    <tr>
      <th>Btc</th>
      <th>Ltc</th>
      <th>Ppc</th>
      <th>Nmc</th>
      <th>Xpm</th>
      <th>Asicminer</th>
      <th>Asicminer small</th>
      <th>Advanced mining corp</th>
      <th>Misc1</th>
      <th>Misc2</th>
      <th>Misc3</th>
      <th>Comment</th>
      <th>Time changed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fiveminute_timed_assets.each do |fiveminute_timed_asset| %>
      <tr>
        <td><%= fiveminute_timed_asset.BTC %></td>
        <td><%= fiveminute_timed_asset.LTC %></td>
        <td><%= fiveminute_timed_asset.PPC %></td>
        <td><%= fiveminute_timed_asset.NMC %></td>
        <td><%= fiveminute_timed_asset.XPM %></td>
        <td><%= fiveminute_timed_asset.AsicMiner %></td>
        <td><%= fiveminute_timed_asset.AsicMiner_small %></td>
        <td><%= fiveminute_timed_asset.Advanced_Mining_Corp %></td>
        <td><%= fiveminute_timed_asset.misc1 %></td>
        <td><%= fiveminute_timed_asset.misc2 %></td>
        <td><%= fiveminute_timed_asset.misc3 %></td>
        <td><%= fiveminute_timed_asset.comment %></td>
        <td><%= fiveminute_timed_asset.time_changed %></td>
        <td><%= link_to 'Show', fiveminute_timed_asset %></td>
        <td><%= link_to 'Edit', edit_fiveminute_timed_asset_path(fiveminute_timed_asset) %></td>
        <td><%= link_to 'Destroy', fiveminute_timed_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fiveminute timed asset', new_fiveminute_timed_asset_path %>

app/views/fiveminute_timed_assets/new.html.erb
<h1>New fiveminute_timed_asset</h1>

<%= render 'form' %>

<%= link_to 'Back', fiveminute_timed_assets_path %>

app/views/fiveminute_timed_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Btc:</strong>
  <%= @fiveminute_timed_asset.BTC %>
</p>

<p>
  <strong>Ltc:</strong>
  <%= @fiveminute_timed_asset.LTC %>
</p>

<p>
  <strong>Ppc:</strong>
  <%= @fiveminute_timed_asset.PPC %>
</p>

<p>
  <strong>Nmc:</strong>
  <%= @fiveminute_timed_asset.NMC %>
</p>

<p>
  <strong>Xpm:</strong>
  <%= @fiveminute_timed_asset.XPM %>
</p>

<p>
  <strong>Asicminer:</strong>
  <%= @fiveminute_timed_asset.AsicMiner %>
</p>

<p>
  <strong>Asicminer small:</strong>
  <%= @fiveminute_timed_asset.AsicMiner_small %>
</p>

<p>
  <strong>Advanced mining corp:</strong>
  <%= @fiveminute_timed_asset.Advanced_Mining_Corp %>
</p>

<p>
  <strong>Misc1:</strong>
  <%= @fiveminute_timed_asset.misc1 %>
</p>

<p>
  <strong>Misc2:</strong>
  <%= @fiveminute_timed_asset.misc2 %>
</p>

<p>
  <strong>Misc3:</strong>
  <%= @fiveminute_timed_asset.misc3 %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @fiveminute_timed_asset.comment %>
</p>

<p>
  <strong>Time changed:</strong>
  <%= @fiveminute_timed_asset.time_changed %>
</p>

<%= link_to 'Edit', edit_fiveminute_timed_asset_path(@fiveminute_timed_asset) %> |
<%= link_to 'Back', fiveminute_timed_assets_path %>