config/routes.rb
Cryptos::Application.routes.draw do
  resources :fiveminute_timed_assets

  resources :timed_assets

  resources :user_infos

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  post 'NUKE', to: 'user_infos#NUKE'
  post 'start_log', to: 'staticpages#start_log'
  post 'do_old_assets_averaging', to: 'staticpages#do_old_assets_averaging'
  post 'NUKE_Averages', to: 'staticpages#NUKE_Averages'
  post 'Setup', to: 'staticpages#Setup'

  get "/homepage", to: 'staticpages#homepage'
  get "/about", to: 'staticpages#about'
  get "/database", to: 'staticpages#database'
  get "/worker_messages.html", to: 'staticpages#worker_messages'
  root 'staticpages#homepage'

  

end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  def NUKE
    UserInfo.all.destroy_all

    UserInfo.create(
      :user => "hak8or",
      :pass => "Coolpassword",
      :BTC => 1.2,
      :LTC => 15.3,
      :PPC => 60,
      :NMC => 15,
      :XPM => 180,
      :AsicMiner => 1,
      :AsicMiner_small => 13,
      :Advanced_Mining_Corp => 470,
      :misc1 => 0,
      :misc2 => 0,
      :misc3 => 0,
      :comment => "First Post!",
      :time_changed => Time.now
    )

    respond_to do |format|
      format.html { redirect_to user_infos_url }
      format.json { head :no_content }
    end
  end

  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.first(200)
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
    @user_info = UserInfo.new
  end

  # GET /user_infos/1/edit
  def edit
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(user_info_params)

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:user, :pass, :BTC, :LTC, :PPC, :NMC, 
        :XPM, :AsicMiner, :AsicMiner_small, :Advanced_Mining_Corp, :misc1, 
        :misc2, :misc3, :comment, :time_changed)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<%= form_for(@user_info) do |f| %>
  <% if @user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% @user_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :pass %><br>
    <%= f.text_field :pass %>
  </div>
  <div class="field">
    <%= f.label :BTC %><br>
    <%= f.text_field :BTC %>
  </div>
  <div class="field">
    <%= f.label :LTC %><br>
    <%= f.text_field :LTC %>
  </div>
  <div class="field">
    <%= f.label :PPC %><br>
    <%= f.text_field :PPC %>
  </div>
  <div class="field">
    <%= f.label :NMC %><br>
    <%= f.text_field :NMC %>
  </div>
  <div class="field">
    <%= f.label :XPM %><br>
    <%= f.text_field :XPM %>
  </div>
  <div class="field">
    <%= f.label :AsicMiner %><br>
    <%= f.number_field :AsicMiner %>
  </div>
  <div class="field">
    <%= f.label :AsicMiner_small %><br>
    <%= f.number_field :AsicMiner_small %>
  </div>
  <div class="field">
    <%= f.label :Advanced_Mining_Corp %><br>
    <%= f.number_field :Advanced_Mining_Corp %>
  </div>
  <div class="field">
    <%= f.label :misc1 %><br>
    <%= f.text_field :misc1 %>
  </div>
  <div class="field">
    <%= f.label :misc2 %><br>
    <%= f.text_field :misc2 %>
  </div>
  <div class="field">
    <%= f.label :misc3 %><br>
    <%= f.text_field :misc3 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :time_changed %><br>
    <%= f.datetime_select :time_changed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_infos/edit.html.erb
<h1>Editing user_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_info %> |
<%= link_to 'Back', user_infos_path %>

app/views/user_infos/index.html.erb
<h1 class="subheader" style="padding-left: 10px">Listing user_infos</h1>

<div class="row full-width" style="margin-left: 20px">
  <div class="large-1 columns">
    <br><br><br><br>
    
  </div>

  <div class="large-11 columns">
    <div style="margin-left:90%">
      <%= button_to "NUKE Users Table", :action => "NUKE" %>
    </div>
    

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Pass</th>
          <th>BTC</th>
          <th>LTC</th>
          <th>PPC</th>
          <th>NMC</th>
          <th>XPM</th>
          <th>AsicMiner</th>
          <th>AsicMiner small</th>
          <th>Advanced Mining Corp</th>
          <th>Misc1</th>
          <th>Misc2</th>
          <th>Misc3</th>
          <th>Comment</th>
          <th>Time changed</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @user_infos.each do |user_info| %>
          <tr>
            <td><%= user_info.user %></td>
            <td><%= user_info.pass %></td>
            <td><%= user_info.BTC %></td>
            <td><%= user_info.LTC %></td>
            <td><%= user_info.PPC %></td>
            <td><%= user_info.NMC %></td>
            <td><%= user_info.XPM %></td>
            <td><%= user_info.AsicMiner %></td>
            <td><%= user_info.AsicMiner_small %></td>
            <td><%= user_info.Advanced_Mining_Corp %></td>
            <td><%= user_info.misc1 %></td>
            <td><%= user_info.misc2 %></td>
            <td><%= user_info.misc3 %></td>
            <td><%= user_info.comment %></td>
            <td><%= user_info.time_changed %></td>
            <td><%= link_to 'Show', user_info %></td>
            <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
            <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <%= link_to 'New User info', new_user_info_path, class: "button radius", style: "margin-left:60%" %>

  </div>

</div>

app/views/user_infos/new.html.erb
<h1 class="subheader" style="padding-left:20px">New user_info</h1>

<div class="row full-width">
	<div class="large-9 columns large-offset-1">
		<%= render 'form' %>

		<%= link_to 'Back', user_infos_path, class: "button radius", style: "margin-left: 93%" %>
	</div>

	<div class="large-2 columns"></div>
</div>

<br>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_info.user %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @user_info.pass %>
</p>

<p>
  <strong>Btc:</strong>
  <%= @user_info.BTC %>
</p>

<p>
  <strong>Ltc:</strong>
  <%= @user_info.LTC %>
</p>

<p>
  <strong>Ppc:</strong>
  <%= @user_info.PPC %>
</p>

<p>
  <strong>Nmc:</strong>
  <%= @user_info.NMC %>
</p>

<p>
  <strong>Xpm:</strong>
  <%= @user_info.XPM %>
</p>

<p>
  <strong>Asicminer:</strong>
  <%= @user_info.AsicMiner %>
</p>

<p>
  <strong>Asicminer small:</strong>
  <%= @user_info.AsicMiner_small %>
</p>

<p>
  <strong>Advanced mining corp:</strong>
  <%= @user_info.Advanced_Mining_Corp %>
</p>

<p>
  <strong>Misc1:</strong>
  <%= @user_info.misc1 %>
</p>

<p>
  <strong>Misc2:</strong>
  <%= @user_info.misc2 %>
</p>

<p>
  <strong>Misc3:</strong>
  <%= @user_info.misc3 %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @user_info.comment %>
</p>

<p>
  <strong>Time changed:</strong>
  <%= @user_info.time_changed %>
</p>

<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>